#!/bin/bash
# Auto-generated by main.py — do not hardcode machine-specific paths in git.
cd "$(cd "$(dirname "$0")" && pwd)"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export PYTHONPATH="$(pwd)"
exec "/opt/homebrew/opt/python@3.13/bin/python3.13" server.py
